# Generated by Django 2.2.7 on 2019-11-28 12:20

from decimal import Decimal
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField(unique=True)),
                ('district', models.TextField(unique=True)),
                ('address', models.TextField(unique=True)),
                ('notes', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('studio', 'Studio'), ('can_ho', 'Căn hộ')], default='can_ho', max_length=50, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(999999999999)])),
                ('status', models.TextField()),
                ('living_rooms', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], default='0', max_length=50, unique=True)),
                ('dinning_rooms', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], default='0', max_length=50, unique=True)),
                ('bed_rooms', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], default='0', max_length=50, unique=True)),
                ('bath_rooms', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], default='0', max_length=50, unique=True)),
                ('toilets', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], default='0', max_length=50, unique=True)),
                ('kitchen', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], default='0', max_length=50, unique=True)),
                ('furniture', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=12)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('apartment_type', models.ForeignKey(db_column='apartment_type', on_delete=django.db.models.deletion.CASCADE, related_name='apartment_type', to='public.ApartmentType', to_field='type')),
                ('location', models.ForeignKey(db_column='apartment_location', on_delete=django.db.models.deletion.CASCADE, related_name='apartment_location', to='public.ApartmentLocation')),
            ],
        ),
    ]
