# Generated by Django 2.2.7 on 2019-11-28 12:31

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(999999999999)])),
                ('apartment', models.ForeignKey(db_column='apartment_id', on_delete=django.db.models.deletion.CASCADE, related_name='apartment_services', to='public.Apartment')),
            ],
        ),
    ]
